version: "3.9"

services:
  fastapi:
    build: .
    container_name: churn_fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  streamlit:
    build: .
    container_name: churn_streamlit
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
